from __future__ import annotations

from typing import Dict, List


TAXONOMY_REGISTRY: List[Dict[str, object]] = [
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "condition_binding",
        "taxonomy_code": "condition_binding",
        "condition": "여러 조건이 동일한 변수 또는 객체에 결합된다",
        "action": "조건을 분리 전개하지 말고 공통 변수 기준으로 재정렬한다",
        "keywords": ["조건", "묶", "공통", "재정렬", "하나의 함수"],
    },
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "target_quantity_fixing",
        "taxonomy_code": "target_quantity_fixing",
        "condition": "중간 계산이 많아질수록 최종 목표량이 흐려질 수 있다",
        "action": "전개 전에 문제의 목표량과 직접 연결되는 관계를 먼저 고정한다",
        "keywords": ["값", "목표", "최대", "최소", "직접", "구하"],
    },
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "structure_recognition",
        "taxonomy_code": "structure_recognition",
        "condition": "표면 계산보다 먼저 봐야 할 관계 구조가 있다",
        "action": "공식 대입 전에 식과 조건이 만드는 구조를 먼저 식별한다",
        "keywords": ["구조", "관계", "틀", "형태", "패턴"],
    },
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "representation_translation",
        "taxonomy_code": "representation_translation",
        "condition": "문장 조건과 수식 표현이 따로 놀면 풀이가 흔들린다",
        "action": "문장 조건을 계산 가능한 표현으로 한 번에 번역한다",
        "keywords": ["문장", "식", "표현", "번역", "옮기"],
    },
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "visual_relation_extraction",
        "taxonomy_code": "visual_relation_extraction",
        "condition": "그래프·도형·표에 계산보다 먼저 읽어야 할 관계가 있다",
        "action": "시각 요소에서 지배 관계를 추출한 뒤 식으로 연결한다",
        "keywords": ["그래프", "도형", "표", "시각", "관계"],
    },
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "function_role_preservation",
        "taxonomy_code": "function_role_preservation",
        "condition": "함수 입력과 출력의 역할이 섞이면 변환이 무너진다",
        "action": "치환과 정리 과정에서도 함수의 입력-출력 역할을 분명히 유지한다",
        "keywords": ["함수", "f(", "g(", "입력", "출력"],
    },
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "strategy_selection",
        "taxonomy_code": "strategy_selection",
        "condition": "여러 풀이 경로 중 비용 차이가 큰 상황이다",
        "action": "전개 전에 대입·비교·구조화 중 가장 싼 전략을 먼저 선택한다",
        "keywords": ["전략", "경로", "비용", "선택", "대입"],
    },
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "case_triggering",
        "taxonomy_code": "case_triggering",
        "condition": "절댓값·부호·구간 등 경우 분기 조건이 숨어 있다",
        "action": "분기 기준을 먼저 선언하고 그 기준에 맞춰 경우를 나눈다",
        "keywords": ["경우", "절댓값", "부호", "구간", "나눈"],
    },
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "restriction_propagation",
        "taxonomy_code": "restriction_propagation",
        "condition": "정의역·범위·정수 조건 같은 제한이 계속 유효하다",
        "action": "모든 변형 단계에서 활성 제한을 같이 끌고 간다",
        "keywords": ["정의역", "범위", "정수", "자연수", "제한"],
    },
    {
        "bucket": "required_doctrines",
        "taxonomy_group": "option_usage",
        "taxonomy_code": "option_usage",
        "condition": "객관식 선택지가 전략 비용을 줄여 줄 수 있다",
        "action": "핵심 구조를 고정한 뒤에만 선택지를 검산 도구로 사용한다",
        "keywords": ["선지", "선택지", "객관식", "검산", "비교"],
    },
    {
        "bucket": "anti_patterns",
        "taxonomy_group": "condition_fragmentation",
        "taxonomy_code": "condition_fragmentation",
        "condition": "같은 대상의 조건을 따로 따라가면 구조를 잃는다",
        "action": "조건을 조각내지 말고 공통 대상 기준으로 묶어서 본다",
        "keywords": ["조건", "따로", "분리", "조각", "묶"],
    },
    {
        "bucket": "anti_patterns",
        "taxonomy_group": "premature_expansion",
        "taxonomy_code": "premature_expansion",
        "condition": "핵심 구조가 안 잡힌 상태의 전개는 비용만 키운다",
        "action": "전개 전에 대칭·증감·특수값 여부를 먼저 점검한다",
        "keywords": ["전개", "길어", "먼저", "특수값", "증감"],
    },
    {
        "bucket": "anti_patterns",
        "taxonomy_group": "target_drift",
        "taxonomy_code": "target_drift",
        "condition": "중간량이 최종 목표량처럼 보이면 계산이 새기 쉽다",
        "action": "매 단계에서 지금 구한 양이 문제의 목표와 직접 연결되는지 확인한다",
        "keywords": ["목표", "중간", "흐려", "직접", "연결"],
    },
    {
        "bucket": "anti_patterns",
        "taxonomy_group": "option_anchoring",
        "taxonomy_code": "option_anchoring",
        "condition": "선택지를 먼저 보면 전략이 선택지 모양에 끌린다",
        "action": "선택지는 구조를 고정한 뒤 검산 단계에서만 본다",
        "keywords": ["선지", "먼저", "끌린", "검산", "구조"],
    },
    {
        "bucket": "anti_patterns",
        "taxonomy_group": "visual_ignoring",
        "taxonomy_code": "visual_ignoring",
        "condition": "그래프나 도형을 장식처럼 보면 핵심 정보를 놓친다",
        "action": "시각 요소를 식보다 먼저 읽고 관계를 언어화한다",
        "keywords": ["그래프", "도형", "장식", "관계", "읽"],
    },
    {
        "bucket": "anti_patterns",
        "taxonomy_group": "function_role_collapse",
        "taxonomy_code": "function_role_collapse",
        "condition": "함수식 정리 중 입력과 출력이 섞이면 해석이 무너진다",
        "action": "변형 전후에 입력-출력 역할이 보존되는지 표시한다",
        "keywords": ["함수", "입력", "출력", "치환", "보존"],
    },
    {
        "bucket": "anti_patterns",
        "taxonomy_group": "late_case_split",
        "taxonomy_code": "late_case_split",
        "condition": "경우를 늦게 나누면 한 경우를 전체로 오인하기 쉽다",
        "action": "분기 기준을 먼저 세우고 그 뒤에만 계산을 진행한다",
        "keywords": ["경우", "늦게", "분기", "기준", "전체"],
    },
    {
        "bucket": "anti_patterns",
        "taxonomy_group": "restriction_drop",
        "taxonomy_code": "restriction_drop",
        "condition": "제한 조건을 중간에 놓치면 불가능한 해가 돌아온다",
        "action": "정의역·부호·정수 조건을 변형 줄마다 붙여서 유지한다",
        "keywords": ["제한", "놓치", "정의역", "부호", "정수"],
    },
    {
        "bucket": "anti_patterns",
        "taxonomy_group": "local_success_false_finish",
        "taxonomy_code": "local_success_false_finish",
        "condition": "마지막 한 줄만 맞다고 해서 원문 조건까지 맞는 것은 아니다",
        "action": "결론을 얻은 뒤 원래 조건 집합으로 다시 대조한다",
        "keywords": ["마지막", "원래 조건", "대조", "검산", "재확인"],
    },
    {
        "bucket": "verification_doctrines",
        "taxonomy_group": "original_condition_recheck",
        "taxonomy_code": "original_condition_recheck",
        "condition": "변형 과정이 길수록 원문 조건과의 불일치가 생길 수 있다",
        "action": "마지막 후보를 원래 조건 전체에 다시 넣어 검증한다",
        "keywords": ["원래 조건", "다시", "검증", "대조", "후보"],
    },
    {
        "bucket": "verification_doctrines",
        "taxonomy_group": "domain_range_check",
        "taxonomy_code": "domain_range_check",
        "condition": "정의역·범위 제약이 답의 가능성을 바로 줄인다",
        "action": "최종 후보가 정의역과 범위 제약을 만족하는지 확인한다",
        "keywords": ["정의역", "범위", "최종", "만족", "제약"],
    },
    {
        "bucket": "verification_doctrines",
        "taxonomy_group": "case_exhaustiveness_check",
        "taxonomy_code": "case_exhaustiveness_check",
        "condition": "경우 나누기 문제는 빠진 경우가 있으면 결론이 틀어진다",
        "action": "분기한 경우가 서로 겹치지 않고 전체를 덮는지 점검한다",
        "keywords": ["경우", "빠진", "전체", "겹치", "분기"],
    },
    {
        "bucket": "verification_doctrines",
        "taxonomy_group": "choice_crosscheck",
        "taxonomy_code": "choice_crosscheck",
        "condition": "객관식은 선택지를 이용한 역검산이 가능하다",
        "action": "구조를 확보한 뒤 선택지와 핵심 조건을 교차 검산한다",
        "keywords": ["선지", "선택지", "역검산", "교차", "객관식"],
    },
    {
        "bucket": "verification_doctrines",
        "taxonomy_group": "special_value_sanity_check",
        "taxonomy_code": "special_value_sanity_check",
        "condition": "특수값 대입이 구조 오류를 빠르게 드러낼 수 있다",
        "action": "경계값이나 대표 특수값을 넣어 결과의 방향을 점검한다",
        "keywords": ["특수값", "경계값", "대입", "방향", "점검"],
    },
    {
        "bucket": "verification_doctrines",
        "taxonomy_group": "sign_monotonicity_check",
        "taxonomy_code": "sign_monotonicity_check",
        "condition": "부호·증감 조건은 계산 실수를 검출하는 데 유용하다",
        "action": "최종 식과 후보가 부호·증감 조건과 모순되지 않는지 확인한다",
        "keywords": ["부호", "증감", "모순", "증가", "감소"],
    },
]


TAXONOMY_BY_CODE = {
    entry["taxonomy_code"]: entry
    for entry in TAXONOMY_REGISTRY
}
